### ISSUE TITLE
List of companies using Smile

### ISSUE THREAD

**Issue by jviotti** [FasterXML/smile-format-specification#15]
Hey there!

I'm collecting a list of companies making use of Smile on production, for research purposes, and Google is not helping much. Are you aware of a bunch of companies using Smile?

**Comment by cowtowncoder** [comment]
The first significant external user (aside from Ning.com that used it internally) was (and as far as I know, is) Elastic (with ElasticSearch and later with Logstash I think). Solr seems to use it too, as well as Storm. These seem like expected optimal use cases (longer streams of loosely structured data).

This as per:

https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/usages

I think Redisson java redis client offers its as one of the options as well.

**Comment by jviotti** [comment]
This helps a lot. Thanks!
