### ISSUE TITLE
Show: Papers covering Smile

### ISSUE THREAD

**Issue by jviotti** [FasterXML/smile-format-specification#18]
Hey there!

As part of my MSc dissertation at University of Oxford, I wrote and published two papers covering the characteristics of various binary serialization formats, including Smile and performing a space-efficiency benchmark, respectively.

Sharing them here in case anybody finds them interesting! The first paper explains how Smile works including an annotated hexadecimal example and the second compares Smile to various other popular serialization formats.

- A Survey of JSON-compatible Binary Serialization Specifications: https://arxiv.org/abs/2201.02089
- A Benchmark of JSON-compatible Binary Serialization Specifications: https://arxiv.org/abs/2201.03051

All the best!

**Comment by cowtowncoder** [comment]
Very cool, thank you for sharing! Would also be of interest to:

    https://groups.google.com/g/smile-format-discussion

**Comment by jviotti** [comment]
Will do! Thanks for the suggestion.

**Comment by cowtowncoder** [comment]
I added links in README; closing this issue. Thanks again!
